// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/audio_relay.proto

package audio

// AudioPacket represents a single audio frame from a client.
type AudioPacket struct {
	UserId      string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	ChannelId   string `protobuf:"bytes,2,opt,name=channel_id,json=channelId" json:"channel_id,omitempty"`
	Seq         uint32 `protobuf:"varint,3,opt,name=seq" json:"seq,omitempty"`
	TimestampMs int64  `protobuf:"varint,4,opt,name=timestamp_ms,json=timestampMs" json:"timestamp_ms,omitempty"`
	SampleRate  uint32 `protobuf:"varint,5,opt,name=sample_rate,json=sampleRate" json:"sample_rate,omitempty"`
	Energy      float32 `protobuf:"fixed32,6,opt,name=energy" json:"energy,omitempty"`
	IsSilence   bool   `protobuf:"varint,7,opt,name=is_silence,json=isSilence" json:"is_silence,omitempty"`
	OpusData    []byte `protobuf:"bytes,8,opt,name=opus_data,json=opusData" json:"opus_data,omitempty"`
}

// MixedAudioPacket is the N-1 mixed output for a specific listener.
type MixedAudioPacket struct {
	ChannelId       string   `protobuf:"bytes,1,opt,name=channel_id,json=channelId" json:"channel_id,omitempty"`
	ListenerUserId  string   `protobuf:"bytes,2,opt,name=listener_user_id,json=listenerUserId" json:"listener_user_id,omitempty"`
	Seq             uint32   `protobuf:"varint,3,opt,name=seq" json:"seq,omitempty"`
	TimestampMs     int64    `protobuf:"varint,4,opt,name=timestamp_ms,json=timestampMs" json:"timestamp_ms,omitempty"`
	SpeakerCount    uint32   `protobuf:"varint,5,opt,name=speaker_count,json=speakerCount" json:"speaker_count,omitempty"`
	ActiveSpeakers  []string `protobuf:"bytes,6,rep,name=active_speakers,json=activeSpeakers" json:"active_speakers,omitempty"`
	MixedOpusData   []byte   `protobuf:"bytes,7,opt,name=mixed_opus_data,json=mixedOpusData" json:"mixed_opus_data,omitempty"`
}
