// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: api/audio_relay.proto

package audio

import (
	"context"

	"google.golang.org/grpc"
)

// AudioRelayClient is the client API for AudioRelay service.
type AudioRelayClient interface {
	RelayAudio(ctx context.Context, opts ...grpc.CallOption) (AudioRelay_RelayAudioClient, error)
}

type audioRelayClient struct {
	cc grpc.ClientConnInterface
}

func NewAudioRelayClient(cc grpc.ClientConnInterface) AudioRelayClient {
	return &audioRelayClient{cc}
}

func (c *audioRelayClient) RelayAudio(ctx context.Context, opts ...grpc.CallOption) (AudioRelay_RelayAudioClient, error) {
	stream, err := c.cc.NewStream(ctx, &AudioRelay_ServiceDesc.Streams[0], "/audio.AudioRelay/RelayAudio", opts...)
	if err != nil {
		return nil, err
	}
	return &audioRelayRelayAudioClient{ClientStream: stream}, nil
}

type AudioRelay_RelayAudioClient interface {
	Send(*AudioPacket) error
	Recv() (*MixedAudioPacket, error)
	grpc.ClientStream
}

type audioRelayRelayAudioClient struct {
	grpc.ClientStream
}

func (x *audioRelayRelayAudioClient) Send(m *AudioPacket) error {
	return x.ClientStream.SendMsg(m)
}

func (x *audioRelayRelayAudioClient) Recv() (*MixedAudioPacket, error) {
	m := new(MixedAudioPacket)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AudioRelayServer is the server API for AudioRelay service.
type AudioRelayServer interface {
	RelayAudio(AudioRelay_RelayAudioServer) error
}

func RegisterAudioRelayServer(s *grpc.Server, srv AudioRelayServer) {
	s.RegisterService(&AudioRelay_ServiceDesc, srv)
}

type AudioRelay_RelayAudioServer interface {
	Send(*MixedAudioPacket) error
	Recv() (*AudioPacket, error)
	grpc.ServerStream
}

type audioRelayRelayAudioServer struct {
	grpc.ServerStream
}

func (x *audioRelayRelayAudioServer) Send(m *MixedAudioPacket) error {
	return x.ServerStream.SendMsg(m)
}

func (x *audioRelayRelayAudioServer) Recv() (*AudioPacket, error) {
	m := new(AudioPacket)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var AudioRelay_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "audio.AudioRelay",
	HandlerType: (*AudioRelayServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RelayAudio",
			Handler:       _AudioRelay_RelayAudio_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/audio_relay.proto",
}

func _AudioRelay_RelayAudio_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AudioRelayServer).RelayAudio(&audioRelayRelayAudioServer{ServerStream: stream})
}
